function [fitresult, gof] = createFit(beari, bear, Mdisp)
%CREATEFIT(BEARI,BEAR,MDISP)
%  Create a fit.
%
%  Data for 'disp consistency' fit:
%      X Input : beari
%      Y Input : bear
%      Z Output: Mdisp
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Nov-2011 00:32:18


%% Fit: 'disp consistency'.
[xData, yData, zData] = prepareSurfaceData( beari, bear, Mdisp );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';
ex = excludedata( xData, yData, 'Indices', 69 );
opts.Exclude = ex;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'disp consistency' );
h = plot( fitresult, [xData, yData], zData, 'Exclude', ex );
legend( h, 'disp consistency', 'Mdisp vs. beari, bear', 'Excluded Mdisp vs. beari, bear', 'Location', 'NorthEast' );
% Label axes
xlabel( 'beari' );
ylabel( 'bear' );
zlabel( 'Mdisp' );
grid on
view( -23.5, 34 );


